# Generated by Django 3.2 on 2023-04-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_f_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='head_image',
            new_name='image',
        ),
    ]
