# Generated by Django 3.2 on 2023-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_f_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='csv',
            field=models.FileField(blank=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
