# Generated by Django 3.2 on 2023-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_f_app', '0002_rename_head_image_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='csv',
            field=models.FileField(blank=True, upload_to='dr_f_app/csv/'),
        ),
    ]
